<?php

    function contactmodule_form_alter(&$form, &$form_state, $form_id) {
        // print '<pre>';
        // print_r($form);
        // print '</pre>';
    if($form_id == 'contact_site_form') {

            //$form['subject']['#type'] = 'hidden';
            //$form['copy']['#type'] = 'hidden';
            $form['subject']['#default_value']= "Feedback";
            $form['copy']['#default_value'] = 1;
        }
    }
